version: '2'
services:
  elasticsearch:
    image: summasolutions/elasticsearch:6.4.2
    ports:
      - "9200:9200"
      - "9300"
#    volumes:
#      - "~/.elasticsearch:/usr/share/elasticsearch/data"
    networks:
      - back

networks:
  back:
    driver: bridge


# MySQL         elasticsearch
# database      Index
# table         Type
# Row           Document
